parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
extends:
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:sonarjs/recommended
  - plugin:security/recommended
plugins:
  - import
  - '@typescript-eslint/eslint-plugin'
settings:
  import/resolver:
    typescript:
      project: import/resolver
env:
  node: true
  jest: true
rules:
  '@typescript-eslint/no-explicit-any': 2
  '@typescript-eslint/no-unused-vars':
    - 2
    - ignoreRestSiblings: true
  eqeqeq: 2
  import/first: 2
  import/namespace: 2
  import/newline-after-import: 2
  import/no-cycle: 2
  import/no-named-as-default-member: 2
  import/order:
    - 2
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
      warnOnUnassignedImports: true
  no-console: 1
  no-debugger: 2
  no-duplicate-imports: 2
  no-else-return: 2
  no-empty-function:
    - 2
    - allow:
        - constructors
  no-extra-boolean-cast: 2
  no-multi-spaces: 2
  no-undefined: 2
  no-unreachable: 2
  no-var: 2
  require-await: 2
  security/detect-object-injection: 0
  sonarjs/cognitive-complexity: 2
  sonarjs/no-collapsible-if: 2
  sonarjs/no-duplicated-branches: 2
  sonarjs/no-duplicate-string: 2
  sonarjs/no-identical-functions: 2
  sonarjs/no-redundant-jump: 2
  sonarjs/no-small-switch: 2
  sonarjs/no-unused-collection: 2
  sonarjs/prefer-immediate-return: 2
